apiVersion: v1
kind: Pod
metadata:
  name: web-app1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: web-app1
spec:
  type: LoadBalancer
  selector:
    app: web-app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
