apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: attacker
  name: attacker
spec:
  containers:
  - command:
    - sleep
    - 1d
    image: us.gcr.io/panw-gcp-team-testing/qwiklab/pcc-log4shell/att-machine:1.0
    name: attacker
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: attacker
spec:
  selector:
    run: attacker
  clusterIP: None
  ports:
  - name: ldap
    port: 1389
    targetPort: 1389
  - name: web
    port: 8888
    targetPort: 8888
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: attacker-svr
  name: attacker-svr
spec:
  containers:
  - image: us.gcr.io/panw-gcp-team-testing/qwiklab/pcc-log4shell/l4s-demo-svr:1.0
    imagePullPolicy: IfNotPresent
    name: attacker-svr
    ports:
    - containerPort: 8888
      protocol: TCP
      name: web
    - containerPort: 1389
      protocol: TCP
      name: ldap